import { AlertTriangle, Bot, FileText, Fingerprint, Gauge, MessageSquare, UploadCloud, Users } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const pages = [
  'Landing Page',
  'Home',
  'Complaint Registration',
  'Financial Fraud Reporting',
  'Women & Child Crime Reporting',
  'Cyber Crime Categories',
  'Complaint Tracking',
  'Evidence Upload',
  'Document Upload',
  'Video Upload',
  'Audio Upload',
  'Screenshot Upload',
  'OTP Verification',
  'Identity Verification',
  'Citizen Dashboard',
  'Complaint Timeline',
  'Complaint Status',
  'Case Details',
  'Investigation Progress',
  'Notifications',
  'Announcements',
  'Emergency Help',
  'FAQ',
  'Knowledge Center',
  'Cyber Safety Tips',
  'Awareness Campaigns',
  'Latest Alerts',
  'News',
  'Downloads',
  'Forms',
  'Contact',
  'Feedback',
  'Chat Support',
  'AI Assistant',
  'Profile',
  'Settings',
  'Security Settings',
  'Multi-language Support',
  'Accessibility Settings',
  'Login',
  'Signup',
  'Forgot Password',
  'OTP Login',
  'Admin Dashboard',
  'Police Dashboard',
  'Officer Dashboard',
  'Analytics Dashboard',
  'Reports',
  'Audit Logs',
  'Activity Timeline',
  'Role Management',
  'Permissions',
  'User Management',
  'Case Assignment',
  'Escalation',
  'Internal Messaging',
  'Search',
  'Advanced Filters',
  'Global Search',
] as const;

export const aiFeatures = [
  'AI Complaint Assistant',
  'Guided Reporting',
  'Fraud/Scam Detection',
  'OCR + Document Analysis',
  'Image & Screenshot Understanding',
  'Evidence Classification',
  'Duplicate Complaint Detection',
  'Case Prioritization',
  'Translation',
  'Voice Reporting',
  'Speech-to-Text',
  'Text-to-Speech',
  'Auto Form Filling',
  'Semantic Knowledge Search',
  'Recommended Actions',
  'Risk Score',
  'Pattern Detection',
  'Incident Summary',
  'Timeline Generation',
  'Smart Notifications',
  'Officer Copilot',
] as const;

export const reportingSteps = [
  'Choose incident',
  'Describe in your language',
  'Upload evidence',
  'Verify identity',
  'Review AI summary',
  'Submit & track',
] as const;

export const timelineStates = ['Submitted', 'AI classified', 'Officer assigned', 'Bank response'] as const;

export const assistantFindings = [
  'Detected: financial fraud / phishing',
  'Suggested: call 1930 and freeze transaction',
  'Next: upload screenshot, SMS, UPI reference',
] as const;

export const flows = [
  {
    name: 'Citizen emergency financial fraud',
    steps: [
      'One-tap 1930 emergency action',
      'AI triage and scam type detection',
      'OTP identity verification',
      'Evidence upload with OCR',
      'Bank/payment details capture',
      'Risk score + acknowledgement',
      'Live case timeline',
    ],
  },
  {
    name: 'Women & child safety report',
    steps: [
      'Trauma-informed entry',
      'Anonymous guidance option',
      'Minimal sensitive questions first',
      'Safe evidence vault',
      'Priority escalation',
      'Support resources',
      'Officer handoff',
    ],
  },
  {
    name: 'Officer investigation',
    steps: [
      'Command center queue',
      'AI summarized complaint',
      'Evidence classifier',
      'Assignment and escalation',
      'Internal messaging',
      'Audit trail',
      'Court-ready report export',
    ],
  },
] as const;

export const tokens = {
  colors: ['trust #2454FF', 'cyber #00D4FF', 'ink #07111F', 'mint #00C48C', 'saffron #FF9F1C', 'danger #E03131'],
  type: ['Display 64/1.0', 'H1 48/1.05', 'H2 34/1.1', 'Body 16/1.65', 'Caption 13/1.4'],
  spacing: ['4', '8', '12', '16', '24', '32', '48', '64', '96', '128'],
  radius: ['12', '16', '24', '32', 'full'],
} as const;

export const commandCenters: Array<{ name: string; Icon: LucideIcon; description: string }> = [
  { name: 'Citizen Dashboard', Icon: Users, description: 'Personal timeline, acknowledgement, evidence vault, notifications and next actions.' },
  { name: 'Officer Copilot', Icon: Fingerprint, description: 'AI summaries, priority queues, assignment context and investigation suggestions.' },
  { name: 'Admin Analytics', Icon: Gauge, description: 'Modern charts, escalation heatmaps, service levels, risk trends and performance reports.' },
  { name: 'Evidence Vault', Icon: UploadCloud, description: 'Secure uploads for documents, video, audio and screenshots with classification.' },
  { name: 'Audit Logs', Icon: FileText, description: 'Immutable activity timeline for RBAC-sensitive workflows and compliance review.' },
  { name: 'Secure Messaging', Icon: MessageSquare, description: 'Internal collaboration between officers, nodal users, banks and support teams.' },
  { name: 'Emergency Desk', Icon: AlertTriangle, description: 'Fast-path financial fraud freeze and women/child safety escalation workflows.' },
  { name: 'AI Assistant', Icon: Bot, description: 'Always-available multilingual guided help for citizens and investigators.' },
];
